# Generated by Django 5.0.6 on 2024-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('volunteer_team', 'Volunteer Team')], default='normal_user', max_length=20),
        ),
    ]
