# Generated by Django 5.0.6 on 2024-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='status',
        ),
        migrations.AddField(
            model_name='member',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
