# Generated by Django 5.0.6 on 2024-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_member_status_member_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
