# Generated by Django 5.0.6 on 2024-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_member_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
