# Generated by Django 5.0.6 on 2024-09-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('normal_user', 'Normal User'), ('volunteer_team', 'Volunteer Team')], default='normal_user', max_length=20),
        ),
    ]
