# Generated by Django 5.0.6 on 2024-09-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
